# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

# environment/computational parameters
seed: 254639       # random number generator seed (long integer value)
device: cuda:0
num_workers: 15

# dataset parameters
num_classes: 2
training_set: "/mnt/machinelearning/Models/Cougar/Experiments/Binary/train.csv"
test_set: "/mnt/machinelearning/Models/Cougar/Experiments/Binary/test.csv"

# training hyperparameters
image_size: [456, 456]
num_epochs: 100
batch_size: 64
learning_rate: 0.003
weight_decay: 0.001

# overwrite .pt files?
overwrite: False
experiment_folder: '/mnt/machinelearning/Models/Cougar/Experiments/Binary'
