method: bayes
program: animl/run_train.py
metric:
  name: loss_val
  goal: minimize
parameters:
  learning_rate:
    min: 0.0001
    max: 0.002
    distribution: log_uniform_values
  weight_decay:
    min: 0.00001
    max: 0.01
    distribution: log_uniform_values
  num_epochs:
    value: 15  # fix n epochs for sweep runs
run_cap: 30