method: bayes
program: animl/run_train.py
metric:
  name: best_val_loss
  goal: minimize
parameters:
  learning_rate:
    min: 0.00001
    max: 0.01
    distribution: log_uniform_values
  weight_decay:
    min: 0.00001
    max: 0.01
    distribution: log_uniform_values